### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by gamees** [talesnsantos/Automatizacao_Instagram#1]
Fui tentar rodar e da o seguinte erro abaixo, alem de n ter o arquivo .txt

Traceback (most recent call last):
  File "bot.py", line 111, in <module>
    instagram.comentario(nome)
NameError: name 'nome' is not defined

**Comment by talesnsantos** [comment]
Bom 

> 
> 
> Fui tentar rodar e da o seguinte erro abaixo, alem de n ter o arquivo .txt
> 
> Traceback (most recent call last):
> File "bot.py", line 111, in
> instagram.comentario(nome)
> NameError: name 'nome' is not defined

**Comment by Tales-Santos-code** [comment]
Bom dia, estarei verificando o erro e corrigindo.
em relação ao arquivo .txt, foi feita uma função na qual se o arquivo não existir ele será criado, caso tenha dado erro nessa parte, solicito que me retorne para que o mesmo possa ser corrigido.

Agradeço o comentário possibilitando novas melhorias.
Atenciosamente,
Tales N Santos.
